python main.py \
    --model gpt-3.5-turbo-instruct \
    --dataset gqa \
    --test_num 100 \
    --stage 3 \
    --inference_prompt_path prompts/gqa/gqa_stage3.prompt \
    --dataset_dir /path/to/gqa/ \
    --ann_path annotations/testdev_balanced_questions.json \
    --image_path images/ \
    --save_output \
    --output_dir save/results/gqa/gqa_stage3/